### ISSUE TITLE
Add support for question files

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-survey#4]
Since we will put the questions in markdown format, we need to prepare to support that. 

- [ ] add the markdown to json addon to the project. 
- [ ] add a data folder to the app

**Comment by ChazJensen** [comment]
This seems easy enough for a first issue. I'll start work on adding it in and submit a pull request in a few days or so.

**Comment by yuriyaran** [comment]
@MelSumner, seems like this ticket is done? and may be closed?
